// Parity gate for Cut B stage B3 (docs/integration-phase1-signin-and-bridge.md),
// same discipline as bip341-psbt-signer's and nostr-transport's own parity
// tests. This module is vendored byte-identically from tapit-wallet's
// tapit-attest/src/core/nip44.ts.
//
// Unlike those two modules, encryptTo has no way to inject deterministic
// randomness (the 32-byte nonce comes from the platform's real CSPRNG), so
// there is no single "golden event id" to assert. The fixtures below were
// generated by ACTUALLY RUNNING both implementations against each other --
// not hand-derived -- and hardcoded here as regression fixtures:
//   1. This package's encryptTo() produced DT_CIPHERTEXT for the fixed
//      sender/recipient/plaintext below.
//   2. Tapit's real, built tapit-attest/dist/core/nip44.js decryptFrom()
//      was run against DT_CIPHERTEXT and recovered the exact plaintext --
//      proven cross-repo compatible, not assumed.
//   3. The reverse was run too: Tapit's encryptTo() produced
//      TAPIT_CIPHERTEXT, and THIS package's decryptFrom() recovered the
//      exact plaintext from it.
// Both directions are asserted below. If this vendored copy ever drifts
// from Tapit's canonical source, one of these two fixed ciphertexts will
// stop decrypting to the expected plaintext, and this test catches it
// without needing to run the other repo's code at test time.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { encryptTo, decryptFrom } from '../dist/nip44.js';

const SENDER_PRIV = '11'.repeat(32);
const SENDER_PUB = '4f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa';
const RECIPIENT_PRIV = '22'.repeat(32);
const RECIPIENT_PUB = '466d7fcae563e5cb09a0d1870bb580344804617879a14949cf22285f1bae3f27';
const PLAINTEXT = '{"v":1,"intent":"psbt-cosign","test":"dynastytrust-nip44-parity-fixture"}';

// Produced by THIS package's encryptTo(); decrypts correctly under Tapit's
// real, built nip44.js (verified by actually running it, not assumed).
const DT_CIPHERTEXT =
  'Ah3P5Zj5WUXMML0YTbRB5X4nFcQYaHXXkMl+5PGdFCX7ODSfD49DM+0v+gk7kgvcufQ0EgXXjz9LXDZiBlLUmGZvbQuU4oEZ2a9DgRKmMBfIPlfygmBpg8igFOr6X+283nTeR0RIhXMn7yb8w/r1RtoB/y0hHzXdS61CJDS/gwoeX/CnoJ/qOpcH89nCq9lVx+3TG/XQ42UGdmbkIXOkV25fyA==';

// Produced by Tapit's real tapit-attest/src/core/nip44.ts encryptTo()
// (built dist, actually executed) for the identical inputs.
const TAPIT_CIPHERTEXT =
  'Av/uCY21BxL4NzYFYmpmCOSB7QTlfz1enyFKOC5ESAAta0Cb0fsD0Nuu4U2bXNSaLZbZu9XEeA0cKy0Doo82djMTYVlQ/seOnZW4p/kiwxt57+sUrAgyamvOqSWnt8oAWKQ7FNq0C7atpxh+xy/DdiqF80ND9vyLFLrAD4iQI0Ys0ZfUXEvzYgbJA4nZalPu0igxeWyq/BMFvhPAcZqbmCUKPw==';

test('encryptTo/decryptFrom round-trips under this package alone', () => {
  const ciphertext = encryptTo(PLAINTEXT, RECIPIENT_PUB, SENDER_PRIV);
  const decrypted = decryptFrom(ciphertext, SENDER_PUB, RECIPIENT_PRIV);
  assert.equal(decrypted, PLAINTEXT);
});

test('THE PARITY GATE -- decrypts a ciphertext this package itself produced (regression fixture, already proven Tapit-compatible)', () => {
  const decrypted = decryptFrom(DT_CIPHERTEXT, SENDER_PUB, RECIPIENT_PRIV);
  assert.equal(decrypted, PLAINTEXT);
});

test('THE PARITY GATE -- decrypts a ciphertext produced by Tapit\'s real nip44.ts', () => {
  const decrypted = decryptFrom(TAPIT_CIPHERTEXT, SENDER_PUB, RECIPIENT_PRIV);
  assert.equal(decrypted, PLAINTEXT);
});

test('decryptFrom rejects a tampered ciphertext (MAC check)', () => {
  const tampered = DT_CIPHERTEXT.slice(0, -4) + 'AAAA';
  assert.throws(() => decryptFrom(tampered, SENDER_PUB, RECIPIENT_PRIV));
});

test('decryptFrom rejects the wrong recipient key', () => {
  const wrongRecipientPriv = '33'.repeat(32);
  assert.throws(() => decryptFrom(DT_CIPHERTEXT, SENDER_PUB, wrongRecipientPriv));
});

test('encryptTo rejects a non-32-byte recipient pubkey', () => {
  assert.throws(() => encryptTo(PLAINTEXT, 'aa', SENDER_PRIV));
});
