import assert from 'node:assert/strict';
import http from 'node:http';
process.env.APP_MASTER_KEY = '11'.repeat(32);
const { createApp } = await import('../apps/api/dist/app.js');
const app = createApp();
const server = http.createServer(app);
await new Promise((resolve) => server.listen(0, resolve));
const { port } = server.address();
const base = `http://127.0.0.1:${port}`;
async function call(path, init) { const response = await fetch(`${base}${path}`, init); return { status: response.status, json: await response.json() }; }
let response = await call('/health');
assert.equal(response.status, 200);
assert.equal(response.json.ok, true);
response = await call('/api/keys/generate', { method: 'POST', headers: { 'content-type': 'application/json', 'x-user-id': 'tester' }, body: JSON.stringify({ label: 'Owner Test Key 1', network: 'testnet' }) });
assert.equal(response.status, 201);
assert.equal(response.json.key.label, 'Owner Test Key 1');
assert.ok(response.json.key.xpub.startsWith('tpub'));
assert.equal(response.json.key.pubkey.length, 66);
const keyId = response.json.key.keyId;
response = await call('/api/keys', { headers: { 'x-user-id': 'tester' } });
assert.equal(response.status, 200);
assert.equal(response.json.keys.length, 1);
assert.equal(Object.hasOwn(response.json.keys[0], 'encryptedPrivateBlob'), false);
response = await call(`/api/keys/${keyId}/archive`, { method: 'POST', headers: { 'x-user-id': 'tester' } });
assert.equal(response.status, 200);
assert.equal(response.json.key.status, 'archived');
response = await call('/api/policies/validate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ version: 1, policyId: 'p1', name: 'Family Test Vault', network: 'testnet', members: [{ memberId: 'm1', displayName: 'Thomas', role: 'owner', active: true }, { memberId: 'm2', displayName: 'Backup', role: 'trustee', active: true }], keys: [{ keyId: 'k1', memberId: 'm1', label: 'Owner', origin: 'software', purpose: 'primary', network: 'testnet' }, { keyId: 'k2', memberId: 'm2', label: 'Backup', origin: 'software', purpose: 'backup', network: 'testnet' }], paths: [{ pathId: 'n1', kind: 'normal', threshold: 2, keyIds: ['k1', 'k2'] }, { pathId: 'i1', kind: 'inheritance', threshold: 1, keyIds: ['k2'], timelock: { type: 'relative', value: 52560 } }], rules: { allowKeyReplacement: true, allowThresholdChange: false, requireAuditTrail: true, requireHumanSummary: true, testMode: true } }) });
assert.equal(response.status, 200);
assert.equal(response.json.ok, true);
server.close();
console.log('api tests passed');
